Fragmento do código

# thehive-config/application.conf

# ==================================
# Configurações do JanusGraph (TheHive Database)
# ==================================
janusgraph {
  storage {
    # Desabilita a compressão.
    # Isso contorna o problema de "Missing sub-option 'class' for the 'compression' option"
    compression-enabled = false
  }
}
