
input {
  beats {
    port => 5044
    # Se precisar, adicione configurações de SSL/TLS aqui
  }
}

output {
  elasticsearch {
    # Aponta para o Elasticsearch na mesma máquina (SOC2)
    hosts => ["http://192.168.24.101:9200"]
    index => "wazuh-alerts-4.x-%{+YYYY.MM.dd}"
  }
}
