# Chave secreta da aplicação. Mude para algo longo e aleatório em produção.
play.http.secret.key="secret123"

# Defina como 'false' se você acessa o Cortex via HTTP.
# Defina como 'true' apenas se você configurou um proxy reverso com HTTPS.
play.http.session.secure=false

# Configuração da conexão com o Elasticsearch
# O nome 'db' é o padrão para a conexão principal do banco de dados.
## ElasticSearch
search {

  uri = "http://192.168.24.101:9200"

  # Deixar o usuário e a senha vazios para desabilitar a autenticação.
  user = ""
  password = ""

  # Nome do índice que o Cortex usará no Elasticsearch.
  # O padrão já é 'cortex', mas é bom deixar explícito.
  index = "cortex"
}



